version: '3'

volumes:
  postgres_data:
    driver: local
  postgres_data_keycloak:
    driver: local

services:
  postgres:
    image: postgres:10
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wildfly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  postgres-keycloak:
    image: postgres:10
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  keycloak:
    image: jboss/keycloak:4.0.0.Final
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 9090:8080
    depends_on:
      - postgres-keycloak   
  wildfly:
    build: .
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - postgres
